### ISSUE TITLE
DB creation

### ISSUE THREAD

**Issue by Insane111090** [Jedaka/NetCracker-Project#1]
design DB schema and tables

**Comment by vganshin** [comment]
![final](https://cloud.githubusercontent.com/assets/1931520/10773863/f5cf85ce-7d0e-11e5-957d-91f83e656632.png)

**Comment by Jedaka** [comment]
![up7kpgsgqtg](https://cloud.githubusercontent.com/assets/7442282/10909250/c8d6a4c8-8248-11e5-9ce5-a262ef3bec9f.jpg)
