### ISSUE TITLE
DB. создание таблиц, связей, схема

### ISSUE THREAD

**Issue by larinme** [Jedaka/NetCracker-Project#5]
Выкладываю скрипты. Здесь все, кроме последовательностей. При необходимости выложу.

**Comment by larinme** [comment]
https://drive.google.com/file/d/0B3GppAib1KvUQ0FuTUZnZzY1V1U/view?usp=sharing
![default](https://cloud.githubusercontent.com/assets/11999124/10921049/7683255c-8284-11e5-937d-8b4fd215fae5.PNG)

**Comment by larinme** [comment]
В некоторых файлах после обсуждения нужно будет убрать последовательности и триггеры

**Comment by Jedaka** [comment]
https://drive.google.com/open?id=0B5Rc2t4yUO5ySkUxc0tLNEV2Y1k

**Comment by larinme** [comment]
Открой доступ
